#!/bin/bash
if [ -e ./db_params.conf ]; then
  . ./db_params.conf 
else 
  echo "Configuration file doesn't exist or its name was changed! Make sure proper file is placed in working directory and has a proper name."
  exit 1
fi

function check_variables(){
  for var in "$@"
  do
    if [ -z "${!var}" ]; then
      echo "$var was not assigned!"
      exit 1 
    fi
  done

}
check_variables DB_NAME DB_PASS DB_USER DB_PING_TABLE DB_IPERF_TABLE 

mosquitto_sub -h localhost -t "stats/#" -v | while read -r topic message; do

data="$message"

IFS=',' read -r min avg max std_dev loss time <<< "$data"

case "$topic" in
	"stats/ping")
		mysql -u"$DB_USER" -p"$DB_PASS" -D $DB_NAME -e "INSERT INTO $DB_PING_TABLE (min, avg, max, std_dev, loss, time) VALUES ($min, $avg, $max, $std_dev, $loss, '$time');"
		echo "Record inserted!"
		;;
	"stats/iperf")
		mysql -u"$DB_USER" -p"$DB_PASS" -D $DB_NAME -e "INSERT INTO $DB_IPERF_TABLE (min, avg, max, std_dev, loss, time) VALUES ($min, $avg, $max, $std_dev, $loss, '$time');"
		echo "Record inserted!"
		;;
	*)
		echo "Unknow MQTT topic: $topic"
		;;
esac
		
done
